### ISSUE TITLE
Inconsistent line endings between Windows and Unix

### ISSUE THREAD

**Issue by craigmc08** [tweag/ormolu#717]
**Describe the bug**
Running ormolu on Windows results in CRLF line endings, but running on Unix systems results in LF line endings.

I looked into why this happens and it's because [Data.Text.IO](https://hackage.haskell.org/package/text-1.2.1.1/docs/Data-Text-IO.html) automatically converts `\n` to the system's line ending conventions (this is not a bug in the text package).

**To Reproduce**
Format the same Haskell source code using Windows and a Unix system with `--mode inplace`. Diffing the resulting files will show the line endings are different.

**Expected behavior**
The line ending used by ormolu should be consistent across all platforms. I'd suggest that LF be used. To do this, [`Data.Text.IO.encodeUtf8`](https://hackage.haskell.org/package/text-1.2.1.1/docs/Data-Text-Encoding.html#v:encodeUtf8) can be used to get a `ByteString` with the correct line endings.

**Environment**
 - OS name + version: Windows 10 / Ubuntu 18.04 LTS in WSL2
 - Version of the code: v0.1.4.1

**Additional context**
N/A

**Comment by amesgen** [comment]
The [with-utf8](https://hackage.haskell.org/package/with-utf8) library would be a good fit for this, as it also takes care of setting the most UTF8-ish encoding when printing to stdout/stderr and reading from stdin. But the released version does not support GHC 9.0 (fixed in the git repo).

**Comment by mrkkrp** [comment]
It appears that the problem is still there: https://github.com/mrkkrp/ormolu-action/runs/3701344467?check_suite_focus=true

**Comment by mrkkrp** [comment]
This is fixed, after all. I was confused by Git's `core.autocrlf`.
